[package]
name = "HW"
version = "0.1.0"
edition = "2021"
# Pour indiquer que le projet utilise no_std
crate-type = ["lib"]

[profile.dev]
panic = "abort"
opt-level = 1
debug = 2

[profile.release]
panic = "abort"
opt-level = "s"

[unstable]
build-std = ["core"]

[features]
atmega = []
esp32 = []
